### ISSUE TITLE
asset_summary returns empty result when _asset_name is not set

### ISSUE THREAD

**Issue by mkungla** [cardano-community/koios-artifacts#105]
*_asset_policy
_asset_name

docs indicates that `_asset_name` is optional, however when leaving `_asset_name` blank result will be empty

**Comment by dostrelith678** [comment]
Leaving out the `_asset_name`, you would search for a no-name `""` asset under that policy. Does one exist for your policy example?

**Comment by mkungla** [comment]
Yeah it does not, was expecting to get all assets for policy when name is not present. 
Dunno can you mark `_asset_name` just thinking may it cause confusion that missing optional field = search asset with empty name?

**Comment by dostrelith678** [comment]
I think we just did it to support different ways of specifying no name because they all made sense - sending a request without `_asset_name`, sending `null` for `_asset_name` and specifying an empty string for `_asset_name`. 

Maybe we can add a line somewhere on the API page... For querying bulk assets under a policy we have the `/asset_policy_information`, but it probably makes sense to add a similar endpoint for `asset_summary` as there is no way to do that search with just the policy right now.

**Comment by rdlrt** [comment]
The absence of asset name should give back royalty (as per [CIP-0027](https://cips.cardano.org/cips/cip27/) ), the field description was updated in #112 .

As for seperate endpoint for policy across all assets, it's slightly more complicated due to gazillion spammy tokens against a single policy on-chain. Will need to tackle it as seperate architecture (crawler for asset policies), as part of #90 - hence, closing here.
