### ISSUE TITLE
BUG: `drep_info` uses diferent field names for mainnet

### ISSUE THREAD

**Issue by fallen-icarus** [cardano-community/koios-artifacts#309]
**Describe the bug**
On preproduction and preview networks, the `drep_info` endpoint returns `meta_url` and `meta_hash` field names. However, on mainnet, these same fields are called `url` and `hash`.

**Expected behavior**
The field names should be exactly the same across the networks.

**Comment by rdlrt** [comment]
We're unfortunately forced into a bit of a rush with version releases, due to software version and fork dates coming out.
We were close to mark v1.2.1 release and had it geared up on preprod, but since then - preview went through a fork, base version requirements changed of underlying components, and we're now in process of finalizing v1.3.0 (that you see on preview).

We did a put a note around unavailability of preview network [here](https://x.com/CardanoKoios/status/1853818107011198993) , we should be able to mark a release in a couple of days to update preprod and then schedule for mainnet with finalized release notes.

**Comment by rdlrt** [comment]
Preview and Preprod are now updated - with mainnet update expected on 29th Nov, please check out release page
